name = "XorPkg"
uuid = "f46fdb89-00eb-4a77-9ce4-0f6cb30e3110"
authors = ["Krishna Praneet Gudipaty"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
